### ISSUE TITLE
plugin startup error: cannot import name 'ShortChannelId' from 'pyln.proto' 

### ISSUE THREAD

**Issue by robotparty** [lightningd/plugins#306]
An example but this issue occurs with all plugins: 

```
Traceback (most recent call last):
  File "/home/lightningd/.lightning/plugins/rebalance/rebalance.py", line 2, in <module>
    from pyln.client import Plugin, Millisatoshi, RpcError
  File "/usr/local/lib/python3.8/dist-packages/pyln/client/__init__.py", line 3, in <module>
    from .gossmap import Gossmap, GossmapNode, GossmapChannel, GossmapNodeId
  File "/usr/local/lib/python3.8/dist-packages/pyln/client/gossmap.py", line 5, in <module>
    from pyln.proto import ShortChannelId, PublicKey
ImportError: cannot import name 'ShortChannelId' from 'pyln.proto' (/home/lightningd/.local/lib/python3.8/site-packages/pyln/proto/__init__.py)
```

lightningd version: v0.10.1-193-gbb307fa
pyln-client: 0.10.1
pyln-proto: 0.10.1

**Comment by robotparty** [comment]
Note that I found a fix for this issue and opened an issue in https://github.com/ElementsProject/lightning describing it: https://github.com/ElementsProject/lightning/issues/4848

**Comment by vincenzopalazzo** [comment]
This should be fixed in the 0.10.2

**Comment by daywalker90** [comment]
This is very outdated for several reasons. We use a uv shebang now to make using python plugins super easy.
