### ISSUE TITLE
Backup Plugin: Broken on lightning v0.11.0

### ISSUE THREAD

**Issue by v4w5gse65g874** [lightningd/plugins#364]
I went to upgrade my node to v0.11.0 today and running my start command gave me a backup plugin failure:

```
root@ubuntu:~# lightningd --encrypted-hsm
2022-05-14T16:52:03.607Z DEBUG   plugin-manager: started(5874) /usr/local/bin/../libexec/c-lightning/plugins/autoclean
2022-05-14T16:52:03.610Z DEBUG   plugin-manager: started(5875) /usr/local/bin/../libexec/c-lightning/plugins/bcli
2022-05-14T16:52:03.614Z DEBUG   plugin-manager: started(5876) /usr/local/bin/../libexec/c-lightning/plugins/fetchinvoice
2022-05-14T16:52:03.617Z DEBUG   plugin-manager: started(5877) /usr/local/bin/../libexec/c-lightning/plugins/funder
2022-05-14T16:52:03.621Z DEBUG   plugin-manager: started(5878) /usr/local/bin/../libexec/c-lightning/plugins/topology
2022-05-14T16:52:03.624Z DEBUG   plugin-manager: started(5879) /usr/local/bin/../libexec/c-lightning/plugins/keysend
2022-05-14T16:52:03.627Z DEBUG   plugin-manager: started(5880) /usr/local/bin/../libexec/c-lightning/plugins/offers
2022-05-14T16:52:03.631Z DEBUG   plugin-manager: started(5881) /usr/local/bin/../libexec/c-lightning/plugins/pay
2022-05-14T16:52:03.634Z DEBUG   plugin-manager: started(5882) /usr/local/bin/../libexec/c-lightning/plugins/txprepare
2022-05-14T16:52:03.637Z DEBUG   plugin-manager: started(5883) /usr/local/bin/../libexec/c-lightning/plugins/spenderp
2022-05-14T16:52:03.745Z DEBUG   plugin-manager: started(5884) /root/repos/plugins/backup/backup.py
Traceback (most recent call last):
  File "/root/repos/plugins/backup/backup.py", line 2, in <module>
    from pyln.client import Plugin
  File "/root/repos/lightning/contrib/pyln-client/pyln/client/__init__.py", line 3, in <module>
    from .gossmap import Gossmap, GossmapNode, GossmapChannel, GossmapNodeId
ModuleNotFoundError: No module named 'pyln.client.gossmap'
2022-05-14T16:52:04.640Z INFO    plugin-backup.py: Killing plugin: exited before replying to getmanifest
2022-05-14T16:52:04.641Z **BROKEN** plugin-backup.py: Plugin marked as important, shutting down lightningd!
Could not initialize the plugins, see above for details.
```

I figured maybe I also needed to pull this repo, so I did, and see a `poetry.lock` file in the backup plugin directory now instead of `requirements.txt` - I have run `poetry install` and things went without a hitch, yet the issue remains.

I also ran this in the backup directory since I had to educate myself a little on poetry, same failure:

```
root@ubuntu:~/repos/plugins/backup# poetry run python3.7 backup.py
The currently activated Python version 3.6.9 is not supported by the project (^3.7).
Trying to find and use a compatible version.
Using python3.7 (3.7.5)
Traceback (most recent call last):
  File "backup.py", line 2, in <module>
    from pyln.client import Plugin
  File "/root/repos/lightning/contrib/pyln-client/pyln/client/__init__.py", line 3, in <module>
    from .gossmap import Gossmap, GossmapNode, GossmapChannel, GossmapNodeId
ModuleNotFoundError: No module named 'pyln.client.gossmap'
```

I still have the right libraries (I think?) installed for pyln:

```
root@ubuntu:~# pip3 list | grep pyln
pyln-bolt7                    1.0.2.186
pyln-client                   0.9.3
pyln-proto                    0.10.2.post0
```

I have also tried `pyln-client` version 0.10.1 per the `poetry.lock` file, to no avail. What is gossmap?

**Comment by v4w5gse65g874** [comment]
I'm closing this issue. I do not know how or why this happened, but for some reason during the `lightning` upgrade process the `contrib/pyln-client` directory had deleted a number of `.py` files including `gossmap.py`. A `git reset` fixed the issue. Really strange, but all is well.
